### PR TITLE
Rus are no more vassals but tributaries

### PR DESCRIPTION
**Pull request by ghost**
done

### CODE REVIEW

**Comment by schwarherz** [comment]
@Whizzer would you mind taking a look at this since it's History related?

**Comment by Whizzer** [comment]
Could you provide some sources, @daniloy ? As far as I can tell, the mongols most definitely conquered all of it, even if only until the empire fell apart.

**Comment by daniloy** [comment]
> 
> 
> Could you provide some sources, @daniloy ? As far as I can tell, the mongols most definitely conquered all of it, even if only until the empire fell apart.

It was based on my interpretation of Mongol Rule found in Charles J. Halperin - Russia and the Golden Horde. The Mongol Impact on Medieval Russian History.

**Comment by daniloy** [comment]
The Mongols left the rule of the Rus intact, but send Baskaki for tax collection 
image

**Comment by daniloy** [comment]
image

**Comment by schwarherz** [comment]
Given the source posted, I'm going to go ahead and approve.

**Review by schwarherz — APPROVED** [review]

**Pull request merged**
